"""Builds the world content of the 35-floor campaign into Assets/_Game/Resources/Data.

    python3 Tools/content/build_world.py            # write dungeon/enemies/skills/quests/text_ko + C# spec allowlist
    python3 Tools/content/build_world.py --check    # build and validate only (no writes)
    python3 Tools/content/build_world.py --maps     # print every floor map
    python3 Tools/content/build_world.py --levels   # main-path level simulation per floor
    python3 Tools/content/build_world.py --pace     # real-time estimate per floor (encounter pacing)
    python3 Tools/content/build_world.py --sheet out.png   # coloured contact sheet of all floor maps

Deterministic: same inputs -> byte-identical outputs. Sources: Tools/content/spec.py (fixed ids) and
Tools/content/world/*.py (maps, solver, enemies, skills, texts, quests). Original rows round-trip: enemies are
re-levelled from world/base_enemies.json, skills/text rows are upserted by id, other rows stay untouched.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
DATA = os.path.join(ROOT, 'Assets', '_Game', 'Resources', 'Data')
sys.path.insert(0, HERE)

import spec  # noqa: E402
from world import enemies as W_enemies, floors as W_floors, quests as W_quests, skills as W_skills, texts as W_texts, solver  # noqa: E402


def load(name):
    with open(os.path.join(DATA, name + '.json'), encoding='utf-8') as f:
        return json.load(f)


def dumps(rows):
    return (json.dumps(rows, ensure_ascii=False, indent=1).replace('\n', '\r\n') + '\r\n').encode('utf-8')


def write(name, rows):
    path = os.path.join(DATA, name + '.json')
    data = dumps(rows)
    with open(path, 'rb') as f:
        if f.read() == data:
            return False
    with open(path, 'wb') as f:
        f.write(data)
    return True


# ------------------------------------------------------------------ enemies
def chapter_tag(row, variant_ch, new_ch):
    if row['id'] in variant_ch:
        return variant_ch[row['id']] or None
    if row['id'] in new_ch:
        return new_ch[row['id']]
    return W_enemies.chapter_of_level(row['level'])


def build_enemies():
    rows = W_enemies.build(spec)
    variant_ch = {v[0]: v[4] for v in spec.VARIANTS}
    new_ch = {m[0]: m[2] for m in spec.NEW_MODELS}
    for r in rows:
        r['_chapter'] = chapter_tag(r, variant_ch, new_ch)
        # '_file' stays the last key, as in the original rows.
        f = r.pop('_file')
        r['_file'] = f
    return rows


def strip(rows):
    out = []
    for r in rows:
        r = dict(r)
        r.pop('_chapter', None)
        out.append(r)
    return out


# ------------------------------------------------------------------ allowlist of ids other workers create
def spec_ids():
    items = set(spec.NEW_ITEMS)
    gear = set()
    for line in spec.GEAR_LINES.values():
        gear |= set(line)
    gear |= set(spec.JOB_WEAPONS.values())
    gear |= set(spec.NEW_ACCESSORIES)
    return sorted(items), sorted(gear)


def write_allowlist():
    items, gear = spec_ids()
    path = os.path.join(ROOT, 'Tools', 'LogicTests', 'SpecIds.cs')
    lines = ['// Generated by Tools/content/build_world.py from Tools/content/spec.py. Do not edit.',
             '// Item / equipment ids the expansion plan fixes; rows are authored by the gear & items work, so',
             '// reference checks accept them before those rows exist in the data.',
             'using System.Collections.Generic;', '', 'namespace Abyss.LogicTests', '{',
             '    public static class SpecIds', '    {',
             '        public static readonly HashSet<string> Items = new HashSet<string>',
             '        {']
    for i in range(0, len(items), 6):
        lines.append('            ' + ' '.join('"%s",' % x for x in items[i:i + 6]))
    lines += ['        };', '        public static readonly HashSet<string> Equipment = new HashSet<string>', '        {']
    for i in range(0, len(gear), 5):
        lines.append('            ' + ' '.join('"%s",' % x for x in gear[i:i + 5]))
    lines += ['        };', '        /// <summary>Job signature weapons (equippable only after a class change).</summary>',
              '        public static readonly HashSet<string> JobWeapons = new HashSet<string>', '        {']
    jw = sorted(spec.JOB_WEAPONS.values())
    for i in range(0, len(jw), 5):
        lines.append('            ' + ' '.join('"%s",' % x for x in jw[i:i + 5]))
    lines += ['        };', '        /// <summary>Party level range (enter, leave) of chapters 1-7 (7 = trial corridor).</summary>',
              '        public static readonly int[][] ChapterLevels =', '        {']
    for ch in spec.CHAPTERS:
        lines.append('            new[] { %d, %d },' % ch['levels'])
    lines += ['        };', '        /// <summary>Chapter boss ids, chapters 1-7.</summary>',
              '        public static readonly string[] ChapterBosses = { %s };' % ', '.join('"%s"' % ch['boss'] for ch in spec.CHAPTERS),
              '        public const int LevelCap = %d;' % spec.LEVEL_CAP, '    }', '}', '']
    data = '\r\n'.join(lines).encode('utf-8')
    old = open(path, 'rb').read() if os.path.exists(path) else b''
    if old != data:
        with open(path, 'wb') as f:
            f.write(data)


# ------------------------------------------------------------------ validation
def validate(enemy_rows, skills, floors, quests, items, equipment, statuses, presentations):
    spec_items, spec_gear = spec_ids()
    known_items = set(items) | set(spec_items)
    known_gear = set(equipment) | set(spec_gear)
    known = known_items | known_gear
    eids = {e['id'] for e in enemy_rows}
    problems = []
    for s in skills.values():
        if s.get('presentation') and s['presentation'] not in presentations:
            problems.append('skill %s presentation %s' % (s['id'], s['presentation']))
        for st in [s.get('status_effect')] + s.get('extra_statuses', []):
            if st and st not in statuses:
                problems.append('skill %s status %s' % (s['id'], st))
    for e in enemy_rows:
        for sk in e['skills'] + [x for p in e.get('phases', []) for x in p['skills']]:
            if sk not in skills:
                problems.append('enemy %s skill %s' % (e['id'], sk))
        if len(e['skill_weights']) not in (0, len(e['skills'])):
            problems.append('enemy %s weights' % e['id'])
        for p in e.get('phases', []):
            if len(p['weights']) not in (0, len(p['skills'])):
                problems.append('enemy %s phase weights' % e['id'])
            for x in p['summon']:
                if x not in eids:
                    problems.append('enemy %s phase summon %s' % (e['id'], x))
        for x in e['summons']:
            if x not in eids:
                problems.append('enemy %s summon %s' % (e['id'], x))
        ids = [d['id'] for d in e['drops']]
        if len(ids) != len(set(ids)) or len(ids) < 4 or not any(d['chance'] == 1.0 for d in e['drops']):
            problems.append('enemy %s drop table' % e['id'])
        if not any(d in known_gear for d in ids):
            problems.append('enemy %s has no gear drop' % e['id'])
        for d in ids:
            if d not in known:
                problems.append('enemy %s drop %s unknown' % (e['id'], d))
        if e.get('model') and e['model'] not in eids:
            problems.append('enemy %s model %s' % (e['id'], e['model']))
    for f in floors:
        res = solver.analyse(f['rows'])
        if not res['ok']:
            problems.append('floor %s %s' % (f['floor_label'], res['problems']))
        for t in f['treasures']:
            for k in list(t['contents']['items']) + list(t['contents']['equipment']):
                if k not in known:
                    problems.append('floor %s treasure %s' % (f['floor_label'], k))
            x, y = t['cell']
            if f['rows'][y][x] != 'T':
                problems.append('floor %s treasure cell' % f['floor_label'])
        for ev in f['events']:
            x, y = ev['cell']
            if f['rows'][y][x] != 'E':
                problems.append('floor %s event cell' % f['floor_label'])
        if sum(r.count('E') for r in f['rows']) != len(f['events']):
            problems.append('floor %s events vs cells' % f['floor_label'])
        if sum(r.count('T') for r in f['rows']) != len(f['treasures']):
            problems.append('floor %s treasures vs cells' % f['floor_label'])
        for st in f['lore_stones']:
            x, y = st['cell']
            if f['rows'][y][x] != 'N':
                problems.append('floor %s lore cell' % f['floor_label'])
        for foe in f['foes']:
            if not solver.check_patrol(f['rows'], [tuple(p) for p in foe['patrol']]):
                problems.append('floor %s foe %s patrol' % (f['floor_label'], foe['id']))
        if f['boss_group'] and sum(r.count('B') for r in f['rows']) != 1:
            problems.append('floor %s boss cell' % f['floor_label'])
    fids = {f['id'] for f in floors}
    for q in quests:
        if q['kind'] in ('kill', 'foe', 'boss') and q['target_id'] not in eids:
            problems.append('quest %s target' % q['id'])
        if q['kind'] == 'collect' and q['target_id'] not in known_items:
            problems.append('quest %s collect target' % q['id'])
        if q['kind'] == 'explore' and q['target_id'] not in fids:
            problems.append('quest %s floor' % q['id'])
        for k in q['reward_items']:
            if k not in known:
                problems.append('quest %s reward %s' % (q['id'], k))
    return problems


# ------------------------------------------------------------------ level simulation (main path)
def level_sim(floors, enemy_rows, verbose=True):
    """Expected party level per floor for a main-path party: every floor explored once (its target number of
    random battles, every event, the FOEs, the mid-boss and the boss). Rare groups count at a 35 % catch rate."""
    by_id = {e['id']: e for e in enemy_rows}
    level, xp = 1, 0
    out = []

    def gain(amount):
        nonlocal level, xp
        if level >= spec.LEVEL_CAP:
            return
        xp += amount
        while level < spec.LEVEL_CAP and xp >= W_enemies.xp_to_next(level):
            xp -= W_enemies.xp_to_next(level)
            level += 1
        if level >= spec.LEVEL_CAP:
            xp = 0

    for f in floors:
        n = int(f['floor_label'][1:-1])
        c = (n - 1) // 5 + 1
        enter = level
        battles = W_floors.TARGET_BATTLES[c]
        groups = f['encounter_groups']
        for b in range(battles):
            g = groups[b % len(groups)]
            rare = [x for x in g if x in W_floors.RARE]
            if rare:
                gain(int(sum(by_id[x]['experience_reward'] for x in g if x not in rare) + 0.35 * sum(by_id[x]['experience_reward'] for x in rare)))
            else:
                gain(sum(by_id[x]['experience_reward'] for x in g))
        for ev in f['events']:
            gain(sum(by_id[x]['experience_reward'] for x in ev['group']))
        for foe in f['foes']:
            gain(int(sum(by_id[x]['experience_reward'] for x in foe['group']) * (1 + foe['power']) / 2))
        boss_level = level
        for x in f['boss_group']:
            gain(by_id[x]['experience_reward'])
        out.append((f['floor_label'], f['area_name'], enter, boss_level if f['boss_group'] else level, level))
    if verbose:
        for label, name, a, b, z in out:
            print('%-5s %-16s enter Lv%2d  %s exit Lv%2d' % (label, name, a, ('boss@Lv%2d' % b) if a != b or True else '', z))
    return out


# ------------------------------------------------------------------ pacing estimate
def pace(floors, verbose=True):
    """Real-time estimate per floor: 0.5 s per walked step, 65 s per random battle, 100 s per event/FOE fight,
    6 min for a boss, 8 s per chest/lore stone."""
    total = 0.0
    out = []
    for f in floors:
        steps = solver.exploration_steps(f['rows'], 0.85) * W_floors.WALK_FACTOR
        per = min(f['min_encounter_steps'] + 1.0 / f['encounter_rate'], f['max_encounter_steps'])
        battles = steps / per
        fixed = (len(f['events']) + len(f['foes'])) * 100 + (360 if f['boss_group'] else 0) + (len(f['treasures']) + len(f['lore_stones'])) * 8
        minutes = (steps * 0.5 + battles * 65 + fixed) / 60.0
        total += minutes
        out.append((f['floor_label'], int(steps), battles, minutes))
        if verbose:
            print('%-5s walk %4d steps  %4.1f random battles  ~%4.1f min' % (f['floor_label'], steps, battles, minutes))
    if verbose:
        print('total ~%.1f h (main story %.1f h)' % (total / 60, sum(m for *_, m in out[:30]) / 60))
    return out


# ------------------------------------------------------------------ contact sheet
COLORS = {'#': (24, 26, 36), '.': (70, 86, 112), 'S': (120, 220, 120), '<': (240, 200, 90), '>': (255, 160, 40),
          'W': (90, 150, 255), 'T': (230, 190, 60), 'E': (220, 70, 70), 'B': (255, 30, 90), 'L': (170, 110, 40),
          'K': (255, 240, 120), 'X': (190, 60, 160), 'H': (60, 220, 200), 'N': (150, 120, 230)}


def contact_sheet(floors, path):
    from PIL import Image, ImageDraw, ImageFont
    cell, cols = 9, 7
    tile = 27 * cell + 16
    rows_n = math.ceil(len(floors) / cols)
    img = Image.new('RGB', (cols * tile + 16, rows_n * (tile + 22) + 60), (12, 12, 18))
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype(os.path.join(ROOT, 'Assets', '_Game', 'Fonts', 'Pretendard-Regular.otf'), 14)
    except OSError:
        font = ImageFont.load_default()
    d.text((12, 8), '35 floors (B1F-B35F)  S start  < up  > down  W warp  T chest  K key  L door  E event  B boss  X trap  H spring  N lore  o FOE  M mid-boss',
           fill=(230, 230, 230), font=font)
    for i, f in enumerate(floors):
        ox = 8 + (i % cols) * tile
        oy = 40 + (i // cols) * (tile + 22)
        d.text((ox, oy), '%s %s (%dx%d)' % (f['floor_label'], f['area_name'], len(f['rows'][0]), len(f['rows'])), fill=(220, 220, 220), font=font)
        oy += 20
        for y, r in enumerate(f['rows']):
            for x, ch in enumerate(r):
                d.rectangle([ox + x * cell, oy + y * cell, ox + x * cell + cell - 2, oy + y * cell + cell - 2], fill=COLORS.get(ch, (255, 0, 255)))
        for foe in f['foes']:
            for p in foe['patrol']:
                cx, cy = ox + p[0] * cell + cell // 2 - 1, oy + p[1] * cell + cell // 2 - 1
                col = (255, 80, 255) if foe['id'].startswith('midboss') else (255, 255, 255)
                d.ellipse([cx - 2, cy - 2, cx + 2, cy + 2], outline=col)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)


# ------------------------------------------------------------------ main
def build():
    original_floors = json.load(open(os.path.join(HERE, 'world', 'base_dungeon.json'), encoding='utf-8'))
    enemy_rows = build_enemies()
    floors, meta = W_floors.build_floors(spec, enemy_rows, original_floors)
    skills_rows = load('skills')
    by = {s['id']: i for i, s in enumerate(skills_rows)}
    for s in W_skills.NEW_SKILLS:
        if s['id'] in by:
            skills_rows[by[s['id']]] = s
        else:
            skills_rows.append(s)
    text = load('text_ko')
    for k, v in W_texts.TEXT.items():
        text[k] = v
    for k, v in W_texts.ENEMY_DESC.items():
        text['enemy_desc_' + k] = v
    for k, v in W_texts.ENEMY_DESC_UPDATE.items():
        text['enemy_desc_' + k] = v
    quests = [dict(q) for q in W_quests.QUESTS]
    return enemy_rows, floors, meta, skills_rows, text, quests


def main(argv):
    enemy_rows, floors, meta, skills_rows, text, quests = build()
    items = {i['id'] for i in load('items')}
    equipment = {e['id'] for e in load('equipment')}
    statuses = {s['id'] for s in load('statuses')}
    presentations = {p['id'] for p in load('presentation')}
    skills = {s['id']: s for s in skills_rows}
    problems = validate(enemy_rows, skills, floors, quests, items, equipment, statuses, presentations)
    for p in problems:
        print('PROBLEM', p)
    if '--maps' in argv:
        for f, m in zip(floors, meta):
            print('%s %s seed=%d states=%d walk=%d steps=%d rate=%.3f max=%d foes=%d' % (
                f['floor_label'], f['area_name'], m['seed'], m['states'], m['walkable'], m['steps'], f['encounter_rate'],
                f['max_encounter_steps'], len(f['foes'])))
            print('\n'.join(f['rows']))
    if '--levels' in argv:
        level_sim(floors, enemy_rows)
    if '--pace' in argv:
        pace(floors)
    if '--sheet' in argv:
        contact_sheet(floors, argv[argv.index('--sheet') + 1])
    if problems:
        return 1
    if '--check' in argv:
        return 0
    changed = [n for n, rows in (('dungeon', floors), ('enemies', strip(enemy_rows)), ('skills', skills_rows),
                                 ('quests', quests), ('text_ko', text)) if write(n, rows)]
    write_allowlist()
    print('written:', ', '.join(changed) or 'nothing changed')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
