// Hunter roster: recruiting (story joins after zone bosses, guild scouts), the active party of four and the
// reserve, bench EXP, and the move of saves made with the four original heroes onto the starting hunters.
// Hunters are heroes.json rows (generated by Tools/content/hunters.py from Tools/content/spec.py HUNTERS).
using System;
using System.Collections.Generic;

namespace Abyss.Logic.Game
{
    /// <summary>A hunter the guild can hire now (or later), for the scout list.</summary>
    public sealed class ScoutOffer
    {
        public HeroDef Hunter;
        public int Price;
        /// <summary>Reached the hunter's zone: may be hired when the party can pay.</summary>
        public bool Unlocked;
    }

    public static class HunterRoster
    {
        /// <summary>Share of a won battle's EXP every benched hunter receives.</summary>
        public const double BenchXpShare = 0.5;

        /// <summary>Old hero ids (the four fantasy heroes) and the starting hunters that take their place in old saves.</summary>
        public static readonly Dictionary<string, string> LegacyHeroes = new Dictionary<string, string>
        {
            { "warrior", "h_dohyun" }, { "mage", "h_seoa" }, { "archer", "h_jiho" }, { "cleric", "h_yuna" },
        };

        /// <summary>Zone (1-based) the party has reached: the zone of the deepest floor.</summary>
        public static int ReachedZone(GameState state) => GameFlow.ChapterOf(state.DeepestFloor);

        public static bool IsRecruited(GameState state, string heroId) => state.Hero(heroId) != null;

        /// <summary>Renames the four original heroes of an old save to the starting hunters (level, job, gear, skills kept).</summary>
        public static void MigrateLegacyHeroes(GameDB db, GameState state)
        {
            foreach (var hero in state.AllHunters())
            {
                if (hero == null || hero.Id == null || db.Heroes.ContainsKey(hero.Id)) continue;
                if (LegacyHeroes.TryGetValue(hero.Id, out var hunter) && db.Heroes.ContainsKey(hunter) && state.Hero(hunter) == null) hero.Id = hunter;
            }
        }

        /// <summary>
        /// Adds a hunter to the guild: it joins at the roster's average level (at least 1), already holding its
        /// start job when that job's level is reached, with its authored starter gear and full vitals. It takes a free
        /// party slot, otherwise waits in the reserve. Returns the new hunter, or null when unknown or already recruited.
        /// </summary>
        public static HeroState Recruit(GameDB db, GameState state, string heroId)
        {
            if (!db.Heroes.TryGetValue(heroId ?? "", out var def) || IsRecruited(state, heroId)) return null;
            int total = 0, count = 0;
            foreach (var h in state.AllHunters()) { total += h.Level; count++; }
            int level = count == 0 ? 1 : Math.Max(1, (int)Math.Round(total / (double)count));
            string cls = db.ClassOf(heroId);
            var hero = new HeroState { Id = heroId, Job = cls, Level = Math.Min(GameState.LevelCap, level), Hp = -1, Mp = -1 };
            foreach (string job in StartJobPath(db, def)) if (db.Jobs[job].RequiredLevel <= hero.Level) hero.Job = job;
            if (state.Party.Count < GameState.PartySize) state.Party.Add(hero);
            else state.Reserve.Add(hero);
            state.RepairHero(db, hero);
            return hero;
        }

        /// <summary>Jobs from the first promotion down to the hunter's start job (empty when it starts as its class).</summary>
        static List<string> StartJobPath(GameDB db, HeroDef def)
        {
            var path = new List<string>();
            string cls = string.IsNullOrEmpty(def.Class) ? def.Id : def.Class;
            string id = def.StartJob;
            while (!string.IsNullOrEmpty(id) && id != cls && db.Jobs.TryGetValue(id, out var job) && job.Hero == cls && !path.Contains(id))
            {
                path.Insert(0, id);
                id = job.Parent;
            }
            return path;
        }

        /// <summary>Story joins: every "boss" hunter whose zone boss has fallen and who is not recruited yet. Returns them.</summary>
        public static List<HeroState> SyncStoryJoins(GameDB db, GameState state)
        {
            var joined = new List<HeroState>();
            foreach (string id in db.RosterOrder)
            {
                var def = db.Heroes[id];
                if (def.JoinKind != "boss" || IsRecruited(state, id) || !state.Flags.Contains(GameFlow.BossFlag(def.JoinZone))) continue;
                var hero = Recruit(db, state, id);
                if (hero != null) joined.Add(hero);
            }
            return joined;
        }

        /// <summary>Scout list: every "scout" hunter not recruited yet, unlocked from its zone on.</summary>
        public static List<ScoutOffer> ScoutOffers(GameDB db, GameState state)
        {
            var output = new List<ScoutOffer>();
            int zone = ReachedZone(state);
            foreach (string id in db.RosterOrder)
            {
                var def = db.Heroes[id];
                if (def.JoinKind != "scout" || IsRecruited(state, id)) continue;
                output.Add(new ScoutOffer { Hunter = def, Price = Math.Max(0, def.ScoutPrice), Unlocked = zone >= def.JoinZone });
            }
            return output;
        }

        /// <summary>Hires a scout hunter at the guild reception. Reasons: scout_unknown, scout_locked, reason_not_enough_gold.</summary>
        public static ServiceResult Scout(GameDB db, GameState state, string heroId)
        {
            ScoutOffer offer = null;
            foreach (var o in ScoutOffers(db, state)) if (o.Hunter.Id == heroId) offer = o;
            if (offer == null) return ServiceResult.Fail("scout_unknown");
            if (!offer.Unlocked) return ServiceResult.Fail("scout_locked");
            if (state.Gold < offer.Price) return ServiceResult.Fail("reason_not_enough_gold");
            state.Gold -= offer.Price;
            Recruit(db, state, heroId);
            return ServiceResult.Ok("scout_done_msg", offer.Hunter.DisplayName);
        }

        /// <summary>
        /// Moves a reserve hunter into the party: into slot <paramref name="partyIndex"/> (the hunter there goes to the
        /// reserve) or appended when the index is past the end and the party has room. Only in town, no battle pending.
        /// </summary>
        public static ServiceResult PutInParty(GameState state, string heroId, int partyIndex)
        {
            if (state.Location != GameLocation.Town || state.PendingBattle != null) return ServiceResult.Fail("roster_town_only");
            int r = state.Reserve.FindIndex(h => h.Id == heroId);
            if (r < 0) return ServiceResult.Fail("unknown_member");
            var hero = state.Reserve[r];
            state.Reserve.RemoveAt(r);
            if (partyIndex >= 0 && partyIndex < state.Party.Count)
            {
                var benched = state.Party[partyIndex];
                state.Party[partyIndex] = hero;
                state.Reserve.Insert(Math.Min(r, state.Reserve.Count), benched);
            }
            else if (state.Party.Count < GameState.PartySize) state.Party.Add(hero);
            else { state.Reserve.Insert(r, hero); return ServiceResult.Fail("roster_party_full"); }
            return ServiceResult.Ok("roster_changed_msg");
        }

        /// <summary>Benches a party member (the party keeps at least one hunter). Only in town.</summary>
        public static ServiceResult Bench(GameState state, string heroId)
        {
            if (state.Location != GameLocation.Town || state.PendingBattle != null) return ServiceResult.Fail("roster_town_only");
            int p = state.Party.FindIndex(h => h.Id == heroId);
            if (p < 0) return ServiceResult.Fail("unknown_member");
            if (state.Party.Count <= 1) return ServiceResult.Fail("roster_last_member");
            state.Reserve.Insert(0, state.Party[p]);
            state.Party.RemoveAt(p);
            return ServiceResult.Ok("roster_changed_msg");
        }

        /// <summary>Swaps two party slots (formation order).</summary>
        public static void SwapSlots(GameState state, int a, int b)
        {
            if (a < 0 || b < 0 || a >= state.Party.Count || b >= state.Party.Count || a == b) return;
            (state.Party[a], state.Party[b]) = (state.Party[b], state.Party[a]);
        }

        /// <summary>Bench EXP after a victory: every reserve hunter gains <see cref="BenchXpShare"/> of the battle EXP.</summary>
        public static void AwardBenchXp(GameDB db, GameState state, int experience)
        {
            int xp = (int)Math.Round(Math.Max(0, experience) * BenchXpShare);
            if (xp <= 0) return;
            foreach (var hero in state.Reserve)
            {
                PartyStats.AwardXp(db, hero, xp);
                PartyStats.SyncLearnedSkills(db, hero);
            }
        }
    }
}
