// Class change (전직) at the Guild: requirements, stat preview and the promotion itself. Jobs come from
// Resources/Data/jobs.json (generated by Tools/content/jobs.py); see PartyStats for the job stat and skill rules.
using System;
using System.Collections.Generic;

namespace Abyss.Logic.Game
{
    /// <summary>One requirement line of a class change ("Lv.15 이상", "전직의 증표 1개", ...).</summary>
    public sealed class JobRequirement
    {
        /// <summary>level | boss | item.</summary>
        public string Kind;
        /// <summary>Player-facing line, already localised.</summary>
        public string Text;
        public bool Met;
        /// <summary>Failure reason id when unmet (job_level, job_boss, job_item).</summary>
        public string Reason;
    }

    /// <summary>A job a hero can move to next, with every requirement and its state.</summary>
    public sealed class JobOption
    {
        public JobDef Job;
        public List<JobRequirement> Requirements = new List<JobRequirement>();
        /// <summary>First unmet requirement's reason id, or "" when the change is possible.</summary>
        public string Reason = "";
        public bool Available => Reason == "";
    }

    /// <summary>Class change rules. Failures change nothing.</summary>
    public static class JobService
    {
        /// <summary>Flag a story/quest script may set instead of (or besides) a bestiary kill: "boss_defeated_&lt;enemy id&gt;".</summary>
        public static string BossDefeatedFlag(string enemyId) => "boss_defeated_" + enemyId;

        /// <summary>
        /// Whether the party has defeated <paramref name="enemyId"/>: a bestiary kill (recorded by every victory) or the
        /// <see cref="BossDefeatedFlag"/>. Keyed on the boss id so it holds wherever the boss stands in the dungeon.
        /// </summary>
        public static bool BossDefeated(GameState state, string enemyId)
        {
            if (string.IsNullOrEmpty(enemyId)) return true;
            if (state.Flags.Contains(BossDefeatedFlag(enemyId))) return true;
            return state.Bestiary.TryGetValue(enemyId, out var entry) && entry != null && entry.Kills > 0;
        }

        /// <summary>Jobs promoted directly from the hero's current job, in jobs.json order.</summary>
        public static List<JobDef> NextJobs(GameDB db, HeroState hero)
        {
            string current = string.IsNullOrEmpty(hero.Job) ? hero.Id : hero.Job;
            var output = new List<JobDef>();
            foreach (var job in db.Jobs.Values)
                if (job.Hero == hero.Id && job.Parent == current) output.Add(job);
            return output;
        }

        /// <summary>Requirement check of moving <paramref name="hero"/> to <paramref name="jobId"/>.</summary>
        public static JobOption Check(GameDB db, GameState state, HeroState hero, string jobId)
        {
            if (!db.Jobs.TryGetValue(jobId ?? "", out var job)) return new JobOption { Reason = "job_unknown" };
            var option = new JobOption { Job = job };
            string current = string.IsNullOrEmpty(hero.Job) ? hero.Id : hero.Job;
            if (job.Hero != hero.Id || job.Parent != current) option.Reason = "job_not_next";
            if (job.RequiredLevel > 1)
                Add(option, "level", $"Lv.{job.RequiredLevel} 이상 (현재 Lv.{hero.Level})", hero.Level >= job.RequiredLevel, "job_level");
            if (!string.IsNullOrEmpty(job.RequiredBoss))
            {
                string boss = db.Enemies.TryGetValue(job.RequiredBoss, out var enemy) ? enemy.DisplayName : job.RequiredBoss;
                Add(option, "boss", $"{boss} 토벌", BossDefeated(state, job.RequiredBoss), "job_boss");
            }
            if (!string.IsNullOrEmpty(job.RequiredItem))
            {
                string item = db.Items.TryGetValue(job.RequiredItem, out var def) ? def.DisplayName : job.RequiredItem;
                int have = state.ItemCount(job.RequiredItem);
                Add(option, "item", $"{item} 1개 (보유 {have}개)", have >= 1, "job_item");
            }
            return option;
        }

        static void Add(JobOption option, string kind, string text, bool met, string reason)
        {
            option.Requirements.Add(new JobRequirement { Kind = kind, Text = text, Met = met, Reason = met ? "" : reason });
            if (!met && option.Reason == "") option.Reason = reason;
        }

        /// <summary>Every next job of the hero with its requirement state.</summary>
        public static List<JobOption> Options(GameDB db, GameState state, HeroState hero)
        {
            var output = new List<JobOption>();
            foreach (var job in NextJobs(db, hero)) output.Add(Check(db, state, hero, job.Id));
            return output;
        }

        /// <summary>Effective stats the hero would have in <paramref name="jobId"/> with the gear it could keep.</summary>
        public static HeroStats PreviewStats(GameDB db, HeroState hero, string jobId)
        {
            var preview = new HeroState { Id = hero.Id, Job = jobId, Level = hero.Level, Equipment = new Dictionary<string, string>(hero.Equipment) };
            foreach (string slot in GameState.EquipSlots)
                if (db.Equipment.TryGetValue(preview.Equipped(slot), out var piece) && !PartyStats.AllowsJob(db, piece, preview)) preview.Equipment[slot] = "";
            return PartyStats.EffectiveStats(db, preview);
        }

        /// <summary>Skills the hero would learn on the spot by changing to <paramref name="jobId"/>.</summary>
        public static List<string> PreviewNewSkills(GameDB db, HeroState hero, string jobId)
        {
            var output = new List<string>();
            var known = PartyStats.SkillsFor(db, hero);
            foreach (string id in PartyStats.SkillsFor(db, hero.Id, jobId, hero.Level)) if (!known.Contains(id)) output.Add(id);
            return output;
        }

        /// <summary>
        /// Promotes a hero: checks the requirements, consumes the item, sets the job, learns the job's skills up to the
        /// current level (keeping every skill already learned), moves gear the new job cannot wear to the bag, and raises
        /// current HP/MP by any gain in the maxima. Only in town, with no battle pending. Reasons: unknown_member,
        /// job_battle, job_unknown, job_not_next, job_level, job_boss, job_item.
        /// Success message: job_changed_msg (hero name, job name).
        /// </summary>
        public static ServiceResult ChangeJob(GameDB db, GameState state, string heroId, string jobId)
        {
            var hero = state.Hero(heroId);
            if (hero == null) return ServiceResult.Fail("unknown_member");
            if (state.Location != GameLocation.Town || state.PendingBattle != null) return ServiceResult.Fail("job_battle");
            var option = Check(db, state, hero, jobId);
            if (!option.Available) return ServiceResult.Fail(option.Reason);
            var job = option.Job;
            var before = PartyStats.EffectiveStats(db, hero);
            if (!string.IsNullOrEmpty(job.RequiredItem)) state.RemoveItem(job.RequiredItem, 1);
            hero.Job = job.Id;
            foreach (string slot in GameState.EquipSlots)
            {
                string worn = hero.Equipped(slot);
                if (!db.Equipment.TryGetValue(worn, out var piece) || PartyStats.AllowsJob(db, piece, hero)) continue;
                hero.Equipment[slot] = "";
                state.AddEquipment(worn, 1);
            }
            PartyStats.SyncLearnedSkills(db, hero);
            var after = PartyStats.EffectiveStats(db, hero);
            if (hero.Hp > 0) hero.Hp += Math.Max(0, after.MaxHp - before.MaxHp);
            hero.Mp += Math.Max(0, after.MaxMp - before.MaxMp);
            PartyStats.ClampVitals(db, hero);
            string heroName = db.Heroes.TryGetValue(heroId, out var def) ? def.DisplayName : heroId;
            return ServiceResult.Ok("job_changed_msg", heroName, job.DisplayName);
        }
    }
}
