// Generated by Tools/content/build_world.py from Tools/content/spec.py. Do not edit.
// Item / equipment ids the expansion plan fixes; rows are authored by the gear & items work, so
// reference checks accept them before those rows exist in the data.
using System.Collections.Generic;

namespace Abyss.LogicTests
{
    public static class SpecIds
    {
        public static readonly HashSet<string> Items = new HashSet<string>
        {
            "camp_tent", "enhance_stone", "enhance_stone_abyss", "enhance_stone_hi", "fallen_feather", "fire_bomb",
            "gargoyle_horn", "holy_water", "ice_bomb", "job_medal", "leviathan_fin", "lord_crown",
            "magic_tonic", "master_seal", "max_ether", "megalixir", "metal_gel", "panacea",
            "pearl", "phoenix_plume", "scale_blue", "seed_guard", "seed_life", "seed_magic",
            "seed_mind", "seed_power", "seed_swift", "shadow_pelt", "siren_feather", "speed_tonic",
            "temple_stone", "thunder_bomb", "trial_emblem", "void_shard", "x_potion",
        };
        public static readonly HashSet<string> Equipment = new HashSet<string>
        {
            "acc_abyss_heart", "acc_berserk_ring", "acc_burn_ward", "acc_counter_charm", "acc_crystal_crown",
            "acc_curse_ward", "acc_dark_amulet", "acc_dragon_fang", "acc_earth_amulet", "acc_exp_charm",
            "acc_freeze_ward", "acc_gold_charm", "acc_holy_amulet", "acc_iron_bangle", "acc_kraken_eye",
            "acc_lich_phylactery", "acc_life_pendant", "acc_mana_spring", "acc_mind_ring", "acc_paralyze_ward",
            "acc_regen_ring", "acc_ribbon", "acc_silence_ward", "acc_sleep_ward", "acc_sniper_scope",
            "acc_sphinx_riddle", "acc_spirit_pendant", "acc_swift_anklet", "acc_thunder_amulet", "acc_tp_crest",
            "armor_chain", "armor_dawn", "armor_dragon", "armor_plate", "armor_rune",
            "armor_scale", "armor_tidal", "armor_void", "bow_composite", "bow_gale",
            "bow_heavens", "bow_hunter", "bow_longshot", "bow_nightfall", "bow_short",
            "bow_star", "bow_thornvine", "bow_tide", "bow_void", "bow_wraith",
            "garb_dawn", "garb_leather", "garb_ranger", "garb_shadow", "garb_tide",
            "garb_void", "garb_wind", "garb_wraith", "mace_blessed", "mace_dawn",
            "mace_grace", "mace_judgment", "mace_pearl", "mace_purifier", "mace_requiem",
            "mace_saint", "mace_seraph", "mace_silver", "mace_verdict", "mace_wood",
            "robe_cloth", "robe_dawn", "robe_mystic", "robe_pearl", "robe_sage",
            "robe_silk", "robe_spirit", "robe_void", "staff_abyss_eye", "staff_arcanum",
            "staff_bone", "staff_coral", "staff_crystal", "staff_hex", "staff_oak",
            "staff_prism", "staff_ruby", "staff_sage", "staff_starlight", "staff_void",
            "sword_aegis", "sword_bronze", "sword_conqueror", "sword_dawn", "sword_flamberge",
            "sword_holy_avenger", "sword_iron", "sword_knight", "sword_ravager", "sword_runic",
            "sword_tidal", "sword_void",
        };
        /// <summary>Job signature weapons (equippable only after a class change).</summary>
        public static readonly HashSet<string> JobWeapons = new HashSet<string>
        {
            "bow_heavens", "bow_longshot", "bow_nightfall", "bow_thornvine", "mace_grace",
            "mace_purifier", "mace_seraph", "mace_verdict", "staff_abyss_eye", "staff_arcanum",
            "staff_hex", "staff_prism", "sword_aegis", "sword_conqueror", "sword_holy_avenger",
            "sword_ravager",
        };
        /// <summary>Party level range (enter, leave) of chapters 1-7 (7 = trial corridor).</summary>
        public static readonly int[][] ChapterLevels =
        {
            new[] { 1, 12 },
            new[] { 12, 24 },
            new[] { 24, 34 },
            new[] { 34, 44 },
            new[] { 44, 54 },
            new[] { 54, 64 },
            new[] { 64, 70 },
        };
        /// <summary>Chapter boss ids, chapters 1-7.</summary>
        public static readonly string[] ChapterBosses = { "forest_guardian", "frost_kraken", "flame_sphinx", "boss", "leviathan", "abyss_lord", "abyss_lord_ex" };
        public const int LevelCap = 70;
    }
}
